name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      
      - name: Convert to PDF
        run: pandoc "テキストサンプル.md" -o output.pdf
      
      - uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: output.pdf
