name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Convert to PDF
        run: pandoc "lesson.md" -o output.pdf
      
      - uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: output.pdf
